lib: [
  "_build/install/default/lib/project/META"
  "_build/install/default/lib/project/dune-package"
  "_build/install/default/lib/project/meal.a"
  "_build/install/default/lib/project/meal.cma"
  "_build/install/default/lib/project/meal.cmi"
  "_build/install/default/lib/project/meal.cmt"
  "_build/install/default/lib/project/meal.cmti"
  "_build/install/default/lib/project/meal.cmx"
  "_build/install/default/lib/project/meal.cmxa"
  "_build/install/default/lib/project/meal.ml"
  "_build/install/default/lib/project/meal.mli"
]
libexec: [
  "_build/install/default/lib/project/meal.cmxs"
]
bin: [
  "_build/install/default/bin/project"
]
